### ISSUE TITLE
How to parse a tag with an attribute and contents?

### ISSUE THREAD

**Issue by Binero** [RReverser/serde-xml-rs#59] opened 2017-12-04 19:06 UTC
How would I get it to parse this example?

```xml
<item name="ATTRIBUTE">CONTENTS</item>
```

If I make a structure `Item`, I cannot get to `Contents` any more.

**Comment by RReverser** [comment] 2017-12-05 02:54
Duplicate of #15 and such?

**Closed** 2017-12-05 10:16 UTC
