### ISSUE TITLE
Boolean fields specified with integers always parse as true

### ISSUE THREAD

**Issue by csssuf** [RReverser/serde-xml-rs#41] opened 2017-08-30 00:01 UTC
Boolean fields specified as integers always seem to parse as true, even with contents of `0`:

```rust
#[macro_use] extern crate serde_derive;
extern crate serde_xml_rs;

#[derive(Debug, Deserialize)]
struct Structure {
    boolean_field: bool,
}

fn main() {
    let s = r##"
        <Structure boolean_field="0">
        </Structure>
    "##;
    let test: Structure = serde_xml_rs::from_reader(s.as_bytes()).unwrap();
    println!("{:#?}", test);
}
```
This test program outputs:
```
Structure {
    boolean_field: true
}
```

**Comment by RReverser** [comment] 2017-08-30 11:45
This seems to be a duplicate of https://github.com/RReverser/serde-xml-rs/pull/18, please see my reasoning there.

**Comment by oli-obk** [comment] 2017-08-30 11:50
Note that you can always use `#[serde(deserialize_with=foo)]` to overwrite the behaviour to match your use case. (See https://serde.rs/field-attrs.html for details on how to do that)

**Closed by oli-obk** 2017-08-30 11:50 UTC
Labels: wontfix
